export enum ProductType {
  AC = 'AC',
  GW = 'GW',
  CPS = 'CPS',
  DL = 'DL',
  WPS = 'WPS',
  THREE_G = '3G',
  TWO_G = '2G',
  ONE_G = '1G',
  WH = 'WH',
  DS = 'DS',
  THREE_3TG = '3GT',
  TWO_2TG = '2GT',
  ONE_1TG = '1GT',
  WL = 'WL',
  GD = 'GD',
  CUR = 'CUR',
  PC = 'PC',
}
