export const allTimeZones = [
  { name: 'International Date Line West', offset: 'GMT-12:00' },
  { name: 'Hawaii', offset: 'GMT-10:00' },
  { name: 'Alaska', offset: 'GMT-09:00' },
  { name: 'Pacific Time (US & Canada)', offset: 'GMT-08:00' },
  { name: 'Arizona', offset: 'GMT-07:00' },
  { name: 'Mountain Time (US & Canada)', offset: 'GMT-07:00' },
  { name: 'Central Time (US & Canada)', offset: 'GMT-06:00' },
  { name: 'Mexico City', offset: 'GMT-06:00' },
  { name: 'Saskatchewan', offset: 'GMT-06:00' },
  { name: 'Eastern Time (US & Canada)', offset: 'GMT-05:00' },
  { name: 'Bogota', offset: 'GMT-05:00' },
  { name: 'Indiana (East)', offset: 'GMT-05:00' },
  { name: 'Atlantic Time (Canada)', offset: 'GMT-04:00' },
  { name: 'Caracas', offset: 'GMT-04:00' },
  { name: 'Santiago', offset: 'GMT-04:00' },
  { name: 'Newfoundland', offset: 'GMT-03:30' },
  { name: 'Brasilia', offset: 'GMT-03:00' },
  { name: 'Buenos Aires', offset: 'GMT-03:00' },
  { name: 'Greenland', offset: 'GMT-03:00' },
  { name: 'Mid-Atlantic', offset: 'GMT-02:00' },
  { name: 'Azores', offset: 'GMT-01:00' },
  { name: 'Cape Verde Is.', offset: 'GMT-01:00' },
  { name: 'Casablanca', offset: 'GMT+00:00' },
  { name: 'Dublin', offset: 'GMT+00:00' },
  { name: 'Lisbon', offset: 'GMT+00:00' },
  { name: 'London', offset: 'GMT+00:00' },
  { name: 'Monrovia', offset: 'GMT+00:00' },
  { name: 'Amsterdam', offset: 'GMT+01:00' },
  { name: 'Belgrade', offset: 'GMT+01:00' },
  { name: 'Berlin', offset: 'GMT+01:00' },
  { name: 'Bratislava', offset: 'GMT+01:00' },
  { name: 'Brussels', offset: 'GMT+01:00' },
  { name: 'Budapest', offset: 'GMT+01:00' },
  { name: 'Copenhagen', offset: 'GMT+01:00' },
  { name: 'Madrid', offset: 'GMT+01:00' },
  { name: 'Paris', offset: 'GMT+01:00' },
  { name: 'Prague', offset: 'GMT+01:00' },
  { name: 'Rome', offset: 'GMT+01:00' },
  { name: 'Sarajevo', offset: 'GMT+01:00' },
  { name: 'Warsaw', offset: 'GMT+01:00' },
  { name: 'West Central Africa', offset: 'GMT+01:00' },
  { name: 'Zagreb', offset: 'GMT+01:00' },
  { name: 'Athens', offset: 'GMT+02:00' },
  { name: 'Bucharest', offset: 'GMT+02:00' },
  { name: 'Cairo', offset: 'GMT+02:00' },
  { name: 'Harare', offset: 'GMT+02:00' },
  { name: 'Helsinki', offset: 'GMT+02:00' },
  { name: 'Jerusalem', offset: 'GMT+02:00' },
  { name: 'Kaliningrad', offset: 'GMT+02:00' },
  { name: 'Kyiv', offset: 'GMT+02:00' },
  { name: 'Pretoria', offset: 'GMT+02:00' },
  { name: 'Riga', offset: 'GMT+02:00' },
  { name: 'Sofia', offset: 'GMT+02:00' },
  { name: 'Tallinn', offset: 'GMT+02:00' },
  { name: 'Vilnius', offset: 'GMT+02:00' },
  { name: 'Baghdad', offset: 'GMT+03:00' },
  { name: 'Istanbul', offset: 'GMT+03:00' },
  { name: 'Kuwait', offset: 'GMT+03:00' },
  { name: 'Minsk', offset: 'GMT+03:00' },
  { name: 'Moscow', offset: 'GMT+03:00' },
  { name: 'Nairobi', offset: 'GMT+03:00' },
  { name: 'Riyadh', offset: 'GMT+03:00' },
  { name: 'St. Petersburg', offset: 'GMT+03:00' },
  { name: 'Tehran', offset: 'GMT+03:30' },
  { name: 'Abu Dhabi', offset: 'GMT+04:00' },
  { name: 'Baku', offset: 'GMT+04:00' },
  { name: 'Muscat', offset: 'GMT+04:00' },
  { name: 'Tbilisi', offset: 'GMT+04:00' },
  { name: 'Yerevan', offset: 'GMT+04:00' },
  { name: 'Kabul', offset: 'GMT+04:30' },
  { name: 'Ekaterinburg', offset: 'GMT+05:00' },
  { name: 'Islamabad', offset: 'GMT+05:00' },
  { name: 'Karachi', offset: 'GMT+05:00' },
  { name: 'Tashkent', offset: 'GMT+05:00' },
  { name: 'Chennai', offset: 'GMT+05:30' },
  { name: 'Kolkata', offset: 'GMT+05:30' },
  { name: 'Mumbai', offset: 'GMT+05:30' },
  { name: 'New Delhi', offset: 'GMT+05:30' },
  { name: 'Sri Jayawardenepura', offset: 'GMT+05:30' },
  { name: 'Kathmandu', offset: 'GMT+05:45' },
  { name: 'Almaty', offset: 'GMT+06:00' },
  { name: 'Astana', offset: 'GMT+06:00' },
  { name: 'Dhaka', offset: 'GMT+06:00' },
  { name: 'Urumqi', offset: 'GMT+06:00' },
  { name: 'Rangoon', offset: 'GMT+06:30' },
  { name: 'Bangkok', offset: 'GMT+07:00' },
  { name: 'Hanoi', offset: 'GMT+07:00' },
  { name: 'Jakarta', offset: 'GMT+07:00' },
  { name: 'Krasnoyarsk', offset: 'GMT+07:00' },
  { name: 'Beijing', offset: 'GMT+08:00' },
  { name: 'Chongqing', offset: 'GMT+08:00' },
  { name: 'Hong Kong', offset: 'GMT+08:00' },
  { name: 'Irkutsk', offset: 'GMT+08:00' },
  { name: 'Kuala Lumpur', offset: 'GMT+08:00' },
  { name: 'Perth', offset: 'GMT+08:00' },
  { name: 'Singapore', offset: 'GMT+08:00' },
  { name: 'Taipei', offset: 'GMT+08:00' },
  { name: 'Ulaan Bataar', offset: 'GMT+08:00' },
  { name: 'Osaka', offset: 'GMT+09:00' },
  { name: 'Sapporo', offset: 'GMT+09:00' },
  { name: 'Seoul', offset: 'GMT+09:00' },
  { name: 'Tokyo', offset: 'GMT+09:00' },
  { name: 'Yakutsk', offset: 'GMT+09:00' },
  { name: 'Adelaide', offset: 'GMT+09:30' },
  { name: 'Darwin', offset: 'GMT+09:30' },
  { name: 'Brisbane', offset: 'GMT+10:00' },
  { name: 'Canberra', offset: 'GMT+10:00' },
  { name: 'Guam', offset: 'GMT+10:00' },
  { name: 'Hobart', offset: 'GMT+10:00' },
  { name: 'Melbourne', offset: 'GMT+10:00' },
  { name: 'Port Moresby', offset: 'GMT+10:00' },
  { name: 'Sydney', offset: 'GMT+10:00' },
  { name: 'Vladivostok', offset: 'GMT+10:00' },
  { name: 'Magadan', offset: 'GMT+11:00' },
  { name: 'New Caledonia', offset: 'GMT+11:00' },
  { name: 'Solomon Is.', offset: 'GMT+11:00' },
  { name: 'Kamchatka', offset: 'GMT+12:00' },
  { name: 'Marshall Is.', offset: 'GMT+12:00' },
  { name: 'Fiji', offset: 'GMT+12:00' },
  { name: 'Auckland', offset: 'GMT+12:00' },
  { name: 'Wellington', offset: 'GMT+12:00' },
  { name: "Nuku'alofa", offset: 'GMT+13:00' },
  { name: 'Samoa', offset: 'GMT+13:00' },
  { name: 'Tokelau Is.', offset: 'GMT+13:00' },
];
